apiVersion: v1
kind: Service
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  type: NodePort
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000




